logging:
    enabled: true
  # logging.level:
  # Debug, Info, Warn, Error, Fatal, Panic : Note that the level is case-sensitive and cumulative #
  # (i.e. if you set it to "Error" it will log all errors, fatal and panic)
    level: Info
    output: "file" # file or stdout if file is used, the logfile must be set with logfile: "/var/log/pvs.log"
    logfile: "/var/log/pvs.log"

firewall:
  enabled: true
# If you only have one interface then the firewall will not block network traffic when the vpn rotates or disconnects
  private_network: "192.168.1.0/24"
  private_network_adaptor: "eth1"

monitoring:
  process_restart_limit: 3

openvpn:
    config_dir: "/usr/bin/pvs/vpn_configs"
    rotate_minutes: 15
    # PVS will monitor the VPN Process to ensure it is always running however,
    # OpenVPN connections can sometimes stall while remaining active for this reason we have introduced a network check
    # in the form of a dns check, this is the interval in minutes that the dns check will be performed
    # if the dns check fails the VPN will be restarted, this value should be less than the rotate_minutes value
    dns_check_minutes: 1
    preferred_configs:
    - "my_expressvpn_austria_udp.ovpn"
    - "my_expressvpn_denmark_udp.ovpn"
    - "my_expressvpn_finland_udp.ovpn"
    - "my_expressvpn_france_-_alsace_udp.ovpn"
    - "my_expressvpn_france_-_marseille_udp.ovpn"
    - "my_expressvpn_germany_-_frankfurt_-_1_udp.ovpn"
    - "my_expressvpn_germany_-_frankfurt_-_3_udp.ovpn"
    - "my_expressvpn_germany_-_nuremberg_udp.ovpn"
    - "my_expressvpn_italy_-_cosenza_udp.ovpn"
    - "my_expressvpn_luxembourg_udp.ovpn"
    - "my_expressvpn_monaco_udp.ovpn"
    - "my_expressvpn_netherlands_-_amsterdam_udp.ovpn"
    - "my_expressvpn_netherlands_-_rotterdam_udp.ovpn"
    - "my_expressvpn_netherlands_-_the_hague_udp.ovpn"
    - "my_expressvpn_norway_udp.ovpn"
    - "my_expressvpn_portugal_udp.ovpn"
    - "my_expressvpn_spain_-_madrid_udp.ovpn"
    - "my_expressvpn_sweden_-_2_udp.ovpn"
    - "my_expressvpn_sweden_udp.ovpn"
    - "my_expressvpn_switzerland_-_2_udp.ovpn"
    - "my_expressvpn_switzerland_udp.ovpn"

    # The following command will return a list of host addresses that have failed to resolve, this can happen when the VPN provider no longer supports that URL and the config file is out of date.
    # You should run this if you experience issues with the VPN not connecting and then remove the offending config files from the preferred_configs list.
    #
    # cat /var/log/pvs.log | grep "Cannot resolve host address:" | sed 's/.*Cannot resolve host address: \([^ ]*\).*/\1/' | sort | uniq -c | sort -nr