version: '3.8'
# Note that there is a seperate config file for the vpn service when used with Docker, the firewall is disabled by default due to docker complications
services:
  pvs:  # Pearson VPN Service
    build:
      context: .
      dockerfile: Dockerfile
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "8080:8080"
